name: Cloud-Nuke Daily Cleanup

on:
  workflow_dispatch:
  pull_request:
  schedule:
    # Runs at 00:00 UTC daily
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  cloud-nuke:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        aws-account:
          - name: niau-sandbox
            role: NIAU_SANDBOX_ROLE
          - name: zozocosme-sandbox
            role: ZOZOCOSME_SANDBOX_ROLE
          - name: zozofit-sandbox
            role: ZOZOFIT_SANDBOX_ROLE
          - name: zozomat-sandbox
            role: ZOZOMAT_SANDBOX_ROLE
          - name: zozometry-sandbox
            role: ZOZOMETRY_SANDBOX_ROLE
    env:
      HOMEBREW_CURLRC: 1
      NIAU_SANDBOX_ROLE: arn:aws:iam::${{ secrets.AWS_NIAU_SANDBOX_ACCOUNT }}:role/${{ secrets.AWS_SANDBOX_OIDC_ROLE }}
      ZOZOCOSME_SANDBOX_ROLE: arn:aws:iam::${{ secrets.AWS_ZOZOCOSME_SANDBOX_ACCOUNT }}:role/${{ secrets.AWS_SANDBOX_OIDC_ROLE }}
      ZOZOFIT_SANDBOX_ROLE: arn:aws:iam::${{ secrets.AWS_ZOZOFIT_SANDBOX_ACCOUNT }}:role/${{ secrets.AWS_SANDBOX_OIDC_ROLE }}
      ZOZOMAT_SANDBOX_ROLE: arn:aws:iam::${{ secrets.AWS_ZOZOMAT_SANDBOX_ACCOUNT }}:role/${{ secrets.AWS_SANDBOX_OIDC_ROLE }}
      ZOZOMETRY_SANDBOX_ROLE: arn:aws:iam::${{ secrets.AWS_ZOZOMETRY_SANDBOX_ACCOUNT }}:role/${{ secrets.AWS_SANDBOX_OIDC_ROLE }}
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl file git gcc

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Setup CURLRC
        run: echo "--netrc-optional" >> ~/.curlrc

      - name: Setup NETRC for Artifactory
        run: echo "${{ secrets.ZOZONZ_ARTIFACTORY_NETRC }}" >> ~/.netrc

      - name: Setup NETRC for GitHub
        run: echo "${{ secrets.ZOZONZ_GITHUB_NETRC }}" >> ~/.netrc

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Set up git
        uses: Homebrew/actions/git-user-config@master

      - name: Install cloud-nuke
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
        run: |
          brew tap gruntwork-io/cloud-nuke
          brew install cloud-nuke

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env[matrix.role] }}
          aws-region: ap-southeast-2

      # Run cloud-nuke
      - name: Run cloud-nuke
        run: |
          cloud-nuke aws \
            --dry-run \
            --exclude-resource-type cloudwatch-loggroup \
            --exclude-resource-type cloudtrail \
            --exclude-resource-type config-recorders \
            --exclude-resource-type config-rules \
            --exclude-resource-type guardduty \
            --exclude-resource-type iam-role \
            --exclude-resource-type macie-member \
            --exclude-resource-type oidcprovider \
            --exclude-resource-type security-hub
