name: Cloud-Nuke Daily Cleanup

on:
  workflow_dispatch:
  pull_request:
  schedule:
    # Runs at 00:00 UTC daily
    - cron: '0 0 * * *'

permissions:
  id-token: write
  contents: read

jobs:
  cloud-nuke:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        aws-account:
          - name: niau-sandbox
            role: arn:aws:iam::054037101480:role/OIDC-CloudNuke
          - name: zozocosme-sandbox
            role: arn:aws:iam::205930623238:role/OIDC-CloudNuke
          - name: zozofit-sandbox
            role: arn:aws:iam::911167926524:role/OIDC-CloudNuke
          - name: zozomat-sandbox
            role: arn:aws:iam::605134455195:role/OIDC-CloudNuke
          - name: zozometry-sandbox
            role: arn:aws:iam::761018869138:role/OIDC-CloudNuke
    env:
      HOMEBREW_CURLRC: 1
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl file git gcc

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Setup CURLRC
        run: echo "--netrc-optional" >> ~/.curlrc

      - name: Setup NETRC for Artifactory
        run: echo "${{ secrets.ZOZONZ_ARTIFACTORY_NETRC }}" >> ~/.netrc

      - name: Setup NETRC for GitHub
        run: echo "${{ secrets.ZOZONZ_GITHUB_NETRC }}" >> ~/.netrc

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Set up git
        uses: Homebrew/actions/git-user-config@master

      - name: Install cloud-nuke
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
        run: brew install cloud-nuke

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ matrix.aws-account.role }}
          aws-region: ap-southeast-2

      # Run cloud-nuke
      - name: Run cloud-nuke
        run: |
          cloud-nuke aws \
            --dry-run \
            --older-than 1h \
            --exclude-resource-type cloudwatch-loggroup \
            --exclude-resource-type cloudtrail \
            --exclude-resource-type config-recorders \
            --exclude-resource-type config-rules \
            --exclude-resource-type guardduty \
            --exclude-resource-type iam-role \
            --exclude-resource-type macie-member \
            --exclude-resource-type oidcprovider \
            --exclude-resource-type security-hub
